"""FORGE Code Generation Engine

Generates code from natural language descriptions using AI models.
Supports multiple programming languages and frameworks.
"""

import re
from typing import Optional, Dict, List


class CodeGenerator:
    """Core code generation engine for FORGE."""

    SUPPORTED_LANGUAGES = [
        "python", "javascript", "typescript", "rust", "go", "java",
        "c", "cpp", "csharp", "ruby", "php", "swift", "kotlin",
        "scala", "haskell", "elixir", "clojure", "lua", "perl", "r"
    ]

    def __init__(self, model: str = "default", temperature: float = 0.7):
        self.model = model
        self.temperature = temperature
        self.context_history: List[Dict] = []

    def generate(self, prompt: str, language: str = "python", context: Optional[str] = None) -> str:
        """Generate code from a natural language prompt.

        Args:
            prompt: Description of the code to generate
            language: Target programming language
            context: Optional additional context (existing code, constraints, etc.)

        Returns:
            Generated code string
        """
        if language.lower() not in self.SUPPORTED_LANGUAGES:
            raise ValueError(f"Unsupported language: {language}. Supported: {', '.join(self.SUPPORTED_LANGUAGES)}")

        request = {
            "prompt": prompt,
            "language": language,
            "context": context,
            "model": self.model,
            "temperature": self.temperature,
        }
        self.context_history.append(request)

        # Build the generation prompt
        system_prompt = self._build_system_prompt(language)
        user_prompt = self._build_user_prompt(prompt, context)

        # In production, this would call an AI model API
        return self._mock_generate(system_prompt, user_prompt, language)

    def _build_system_prompt(self, language: str) -> str:
        return (
            f"You are an expert {language} developer. "
            f"Generate clean, well-documented, production-ready code. "
            f"Follow best practices and design patterns for {language}."
        )

    def _build_user_prompt(self, prompt: str, context: Optional[str] = None) -> str:
        parts = [prompt]
        if context:
            parts.insert(0, f"Context:\n{context}\n\nRequest:")
        return "\n".join(parts)

    def _mock_generate(self, system: str, user: str, language: str) -> str:
        """Mock code generation for demonstration."""
        templates = {
            "python": '''def solve(problem: str) -> dict:
    """Auto-generated solution by FORGE.

    Args:
        problem: Description of the problem to solve

    Returns:
        Dictionary containing the solution
    """
    # Analyze the problem
    components = analyze(problem)

    # Generate solution
    result = process(components)

    return {"status": "success", "solution": result}


def analyze(problem: str) -> list:
    """Break down the problem into components."""
    return problem.split()


def process(components: list) -> str:
    """Process components into a solution."""
    return " ".join(reversed(components))
''',
            "javascript": '''/**
 * Auto-generated by FORGE
 * @param {string} problem - The problem to solve
 * @returns {Object} Solution result
 */
function solve(problem) {
    const components = analyze(problem);
    const result = process(components);

    return { status: "success", solution: result };
}

function analyze(problem) {
    return problem.split(" ");
}

function process(components) {
    return components.reverse().join(" ");
}

module.exports = { solve, analyze, process };
''',
            "rust": '''/// Auto-generated by FORGE
/// Solve a given problem and return the result
pub fn solve(problem: &str) -> Solution {
    let components = analyze(problem);
    let result = process(&components);

    Solution {
        status: "success".to_string(),
        solution: result,
    }
}

fn analyze(problem: &str) -> Vec<&str> {
    problem.split_whitespace().collect()
}

fn process(components: &[&str]) -> String {
    components.iter().rev().cloned().collect::<Vec<_>>().join(" ")
}

pub struct Solution {
    pub status: String,
    pub solution: String,
}
''',
        }
        return templates.get(language, f"// Generated {language} code by FORGE\n// Implementation here\n")

    def list_languages(self) -> list:
        return self.SUPPORTED_LANGUAGES.copy()
